services:
  - type: web
    name: zodiac-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Zodiac Store"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:v2wnxLgvosuCcpLQIRtCxaeJxHpBQNmhFpyCLQxDdFY=
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      # Gmail SMTP for OTP password reset emails
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USERNAME
        value: "Sopheareaksapheak@gmail.com"
      - key: MAIL_PASSWORD
        value: "azhteistzzyqiyrz"
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_FROM_ADDRESS
        value: "Sopheareaksapheak@gmail.com"
      - key: MAIL_FROM_NAME
        value: "Zodiac Store"
      # Bakong KHQR
      - key: BAKONG_ACCOUNT_ID
        value: "sopheareaksa_pheak@bkrt"
      - key: BAKONG_ACCOUNT_TYPE
        value: "individual"
      - key: BAKONG_MERCHANT_NAME
        value: "Sopheareaksa Pheak"
      - key: BAKONG_MERCHANT_CITY
        value: "Phnom Penh"
      - key: BAKONG_API_URL
        value: "https://api-bakong.nbc.gov.kh"
      - key: BAKONG_API_TOKEN
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiYWM1YTBhMTczYjA5NDUxNyJ9LCJpYXQiOjE3ODcyMTMwNDEsImV4cCI6MTc5NDk4OTA0MX0.jgqpOE7oIQ52gim8NjX9NyKHHwG2Ff7wtzN5nNdgF24"
      # Telegram Bot
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
