services:
  - type: web
    name: zodiac-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Zodiac Store"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:v2wnxLgvosuCcpLQIRtCxaeJxHpBQNmhFpyCLQxDdFY=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      - key: BAKONG_ACCOUNT_ID
        value: "sopheareaksa_pheak@bkrt"
      - key: BAKONG_ACCOUNT_TYPE
        value: "individual"
      - key: BAKONG_MERCHANT_NAME
        value: "Sopheareaksa Pheak"
      - key: BAKONG_MERCHANT_CITY
        value: "Phnom Penh"
      - key: BAKONG_API_URL
        value: "https://api-bakong.nbc.gov.kh"
      - key: BAKONG_API_TOKEN
        sync: false
