services:
  - type: web
    name: zodiac-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Zodiac Store"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:v2wnxLgvosuCcpLQIRtCxaeJxHpBQNmhFpyCLQxDdFY=
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      # Gmail SMTP for OTP password reset emails
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: "Zodiac Store"
      # Bakong KHQR
      - key: BAKONG_ACCOUNT_ID
        value: "sopheareaksa_pheak@bkrt"
      - key: BAKONG_ACCOUNT_TYPE
        value: "individual"
      - key: BAKONG_MERCHANT_NAME
        value: "Sopheareaksa Pheak"
      - key: BAKONG_MERCHANT_CITY
        value: "Phnom Penh"
      - key: BAKONG_API_URL
        value: "https://api-bakong.nbc.gov.kh"
      - key: BAKONG_API_TOKEN
        sync: false
      # Telegram Bot
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
